import type { ContentType } from './types';

export type HardToPlaceDestination = 'photo-coach' | 'video-coach' | 'create' | 'adoption-bio' | 'profile' | 'update' | 'saved-content' | 'marketing-activity';

export interface HardToPlaceAction {
  label: string;
  destination: HardToPlaceDestination;
  kind?: ContentType;
  context?: string;
  goalId?: string;
}

export interface HardToPlacePlaybook {
  id: string;
  title: string;
  whatMayHelp: string;
  nextSteps: readonly string[];
  actions: readonly HardToPlaceAction[];
}

const factualContext = (focus: string): string => `${focus}\nUse only the foster information already saved in Foster Famous. Do not invent facts, restrictions, or compatibility.`;

export const HARD_TO_PLACE_PLAYBOOKS: readonly HardToPlacePlaybook[] = [
  { id: 'no-views', title: 'No Views / Very Little Reach', whatMayHelp: 'Foster Famous cannot see social-network reach. A fresh, clear post and a broader audience choice can make it easier for the right people to notice.', nextSteps: ['Use a strong hero photo with a clear face.', 'Create a short, factual introduction post.', 'Try a local community audience you already use.', 'Record confirmed activity so your history stays useful.'], actions: [{ label: 'Open Photo Coach', destination: 'photo-coach', goalId: 'hero-adoption-photo' }, { label: 'Create Introduction Post', destination: 'create', kind: 'Social Media Post', context: factualContext('Create a warm introduction post.') }, { label: 'Open Marketing Activity', destination: 'marketing-activity' }] },
  { id: 'views-no-applications', title: 'Views but No Applications', whatMayHelp: 'If people are seeing a post but not taking the next step, clarity can help. Make the adoption information, current status, and right-home details easy to understand.', nextSteps: ['Check that the adoption bio is current.', 'Make the rescue, contact method, or listing link clear.', 'Share known personality and ideal-home information honestly.', 'Use only observed compatibility information.'], actions: [{ label: 'Open Adoption Bio', destination: 'adoption-bio' }, { label: 'Edit Profile', destination: 'profile' }, { label: 'Create Ideal Home Post', destination: 'create', kind: 'Petfinder / Rescue Listing', context: factualContext('Create an ideal-home post using known profile information only.') }] },
  { id: 'shares-no-applications', title: 'Shares but No Applications', whatMayHelp: 'Shares can help more people learn about a foster, but Foster Famous cannot see why someone did or did not apply. A current, specific listing can help the right home self-select.', nextSteps: ['Refresh the adoption bio with current information.', 'Include a clear, factual next step to inquire.', 'Show everyday life, not only posed photos.', 'Keep needs and considerations accurate and visible.'], actions: [{ label: 'Refresh Adoption Bio', destination: 'adoption-bio' }, { label: 'Open Photo Coach', destination: 'photo-coach', goalId: 'relaxing-indoors' }, { label: 'Create Everyday-Life Post', destination: 'create', kind: 'Social Media Post', context: factualContext('Create an everyday-life post with a clear factual adoption next step.') }] },
  { id: 'shy', title: 'Shy / Reserved Foster', whatMayHelp: 'Shyness is not a defect. Quiet, honest home-life content can help people understand the foster’s pace and appreciate their real personality.', nextSteps: ['Capture a calm home-life photo at the foster’s pace.', 'Try a short calm video without pushing interaction.', 'Share known routines or real progress.', 'Describe expectations accurately without promising compatibility.'], actions: [{ label: 'Capture a Calm Photo', destination: 'photo-coach', goalId: 'calm-moment' }, { label: 'Open Video Coach', destination: 'video-coach' }, { label: 'Create Gentle Personality Post', destination: 'create', kind: 'Heartwarming Post', context: factualContext('Create gentle personality or progress content for a shy or reserved foster. Do not frame shyness as a defect.') }] },
  { id: 'senior', title: 'Senior Foster', whatMayHelp: 'A senior foster’s routines, comfort, and companionship can be meaningful to the right adopter. Let documented daily life lead the story.', nextSteps: ['Capture a relaxed everyday-life photo.', 'Share a known favorite routine or comfort.', 'Keep health and care information accurate.', 'Make the adoption next step easy to find.'], actions: [{ label: 'Open Photo Coach', destination: 'photo-coach', goalId: 'relaxing-indoors' }, { label: 'Create Everyday-Life Post', destination: 'create', kind: 'Heartwarming Post', context: factualContext('Create a warm senior-foster everyday-life post using only saved facts.') }, { label: 'Open Adoption Bio', destination: 'adoption-bio' }] },
  { id: 'medical', title: 'Medical / Special Needs', whatMayHelp: 'Clear, accurate information builds trust. Share what daily life looks like and what the foster can do, while keeping documented needs visible. Foster Famous does not provide medical advice.', nextSteps: ['Update Current Status with documented information.', 'Review the adoption bio for accuracy.', 'Show normal daily life when appropriate.', 'Share documented progress only when it exists.'], actions: [{ label: 'Add Foster Update', destination: 'update' }, { label: 'Open Adoption Bio', destination: 'adoption-bio' }, { label: 'Create Daily-Life Post', destination: 'create', kind: 'Social Media Post', context: factualContext('Create a factual daily-life post for a foster with medical or special needs. Do not minimize or add medical claims.') }] },
  { id: 'long-stay', title: 'Long Stay', whatMayHelp: 'A long stay does not define the foster. Fresh, truthful angles can help new people meet the same wonderful individual without louder or guilt-based messaging.', nextSteps: ['Refresh a strong older post with current information.', 'Share a different personality or routine angle.', 'Try a short video if you have mostly photo content.', 'Use a relevant local audience you already use.'], actions: [{ label: 'Open Saved Content', destination: 'saved-content' }, { label: 'Open Video Coach', destination: 'video-coach' }, { label: 'Create Fresh Post', destination: 'create', kind: 'Social Media Post', context: factualContext('Create a fresh, positive post without guilt-based wording.') }] },
  { id: 'hard-to-photograph', title: 'Hard to Photograph', whatMayHelp: 'A perfect posed photo is not necessary. Clear light, eye-level angles, and short video clips can often show personality better.', nextSteps: ['Use bright indirect or natural light.', 'Get down to eye level.', 'Capture one clear face photo.', 'Capture one full-body photo.', 'Try a 5–10 second video if still photos are difficult.'], actions: [{ label: 'Open Photo Coach', destination: 'photo-coach', goalId: 'face-close-up' }, { label: 'Open Video Coach', destination: 'video-coach' }, { label: 'Create a Post', destination: 'create', kind: 'Social Media Post', context: factualContext('Create a post from a clear, honest moment.') }] },
  { id: 'dark-coat', title: 'Black/Dark-Coated Pet Photography', whatMayHelp: 'Thoughtful light and contrast can help the foster’s eyes and expression come through. Coat color does not determine adoptability.', nextSteps: ['Use bright indirect light or safe outdoor shade.', 'Avoid very dark backgrounds.', 'Focus on the eyes and face.', 'Keep the background uncluttered.', 'Try a short video as an alternative.'], actions: [{ label: 'Open Photo Coach', destination: 'photo-coach', goalId: 'face-close-up' }, { label: 'Open Video Coach', destination: 'video-coach' }] },
  { id: 'high-energy', title: 'High-Energy Foster', whatMayHelp: 'Energy can be a great fit for the right home. Show it honestly alongside any known routines, skills, and lifestyle needs.', nextSteps: ['Capture safe play or movement.', 'Add a short video clip.', 'Share known training or routine details.', 'Describe a suitable home only from saved information.'], actions: [{ label: 'Open Video Coach', destination: 'video-coach' }, { label: 'Open Photo Coach', destination: 'photo-coach', goalId: 'playing' }, { label: 'Create Ideal Home Post', destination: 'create', kind: 'Petfinder / Rescue Listing', context: factualContext('Create an ideal-home post for a high-energy foster using known facts only.') }] },
  { id: 'other', title: 'Other / Not Sure', whatMayHelp: 'Foster Famous cannot diagnose social-media performance or adopter behavior. Start with the useful information you already have: profile completeness, current content, media, and confirmed activity.', nextSteps: ['Review the Foster Famous Score for the largest recorded gap.', 'Check for a hero photo and a short video.', 'Refresh a stale adoption bio.', 'Review confirmed Marketing Activity.'], actions: [{ label: 'Review Foster Profile', destination: 'profile' }, { label: 'Open Photo Coach', destination: 'photo-coach', goalId: 'hero-adoption-photo' }, { label: 'Open Marketing Activity', destination: 'marketing-activity' }] },
];
